/*
 * This source file was generated by the Gradle 'init' task
 */
package projectabc;
import javafx.application.Application;
import javafx.stage.Stage;

public class Main extends Application {

    @Override
    public void start(Stage primaryStage) {
        new AuthApp(primaryStage);
    }

    public static void main(String[] args) {
        launch(args);
    }
}
    // pub
    // lic static void main(String[] args) {
    //     Application.launch(AuthApp.class, args);
    // }
    
// }
