/*
 * This source file was generated by the Gradle 'init' task
 */
package projectabc;
import javafx.application.Application;

public class Main {
    public static void main(String[] args) {
        Application.launch(AuthApp.class, args);
    }
    
}
